describe('Edit animal', () => {
  it('login', () => {
    cy.visit('http://localhost:3000')
    cy.get('[id="login-login-input"]').clear().type('Zbyszek')
    cy.get('[id="password-login-input"]').clear().type('Zbyszek')
    cy.get('[id="login-btn"]').click()
    cy.get('[id="logout-btn"]').should('contain.text', 'Logout')
  })
  it('logout', () => {
    cy.visit('/app')
    cy.get('[id="logout-btn"]').click()
    cy.get('[id="login-btn"]')
  })
  it('edit animal page', () => {
    cy.visit('/app')
    cy.get('[id="animal-edit-btn"]').should('contain.text', 'Edit').click({multiple: true, force: true})
    cy.get('[class="modal-header"]').should('contain.text', 'Edit Animal')
  })
  it('edit animal page - empty name - error', () => {
    cy.visit('/app')
    cy.get('[id="animal-edit-btn"]').should('contain.text', 'Edit').click({multiple: true, force: true})
    cy.get('[class="modal-header"]').should('contain.text', 'Edit Animal')
    cy.get('[id="nameLabel-Animal"]').clear()
    cy.get('[id="animal-edit-submit"]').click()
    cy.get('[id="edit-Animal-errMsg"]').should('contain.text', 'Animal name cannot be empty!')
  })
  it('edit animal page - no changes - error', () => {
    cy.visit('/app')
    cy.get('[id="animal-edit-btn"]').should('contain.text', 'Edit').click({multiple: true, force: true})
    cy.get('[class="modal-header"]').should('contain.text', 'Edit Animal')
    cy.get('[id="animal-edit-submit"]').click()
    cy.get('[id="edit-Animal-errMsg"]').should('contain.text', 'You need to apply some changes!')
  })
  it('edit animal page - changes - success', () => {
    cy.visit('/app')
    cy.get('[id="animal-edit-btn"]').should('contain.text', 'Edit').click({multiple: true, force: true})
    cy.get('[class="modal-header"]').should('contain.text', 'Edit Animal')
    cy.get('[id="nameLabel-Animal"]').clear().type('Zbyszek')
    cy.get('[id="animal-edit-submit"]').click()
  })
  it('edit caretaker page', () => {
    cy.visit('/app')
    cy.get('[id="nav-caretaker"]').click()
    cy.get('[id="caretaker-edit-btn"]').should('contain.text', 'Edit').click({multiple: true, force: true})
    cy.get('[class="modal-header"]').should('contain.text', 'Edit caretaker')
  })
  it('edit caretaker page - empty name - error', () => {
    cy.visit('/app')
    cy.get('[id="nav-caretaker"]').click()
    cy.get('[id="caretaker-edit-btn"]').should('contain.text', 'Edit').click({multiple: true, force: true})
    cy.get('[class="modal-header"]').should('contain.text', 'Edit caretaker')
    cy.get('[id="caretakerNameLabel"]').clear()
    cy.get('[id="editCaretakerSubmit"]').click()
    cy.get('[id="edit-Caretaker-errMsg"]').should('contain.text', 'Name cannot be empty!')
  })
  it('edit caretaker page - no changes - success', () => {
    cy.visit('/app')
    cy.get('[id="nav-caretaker"]').click()
    cy.get('[id="caretaker-edit-btn"]').should('contain.text', 'Edit').click({multiple: true, force: true})
    cy.get('[class="modal-header"]').should('contain.text', 'Edit caretaker')
    cy.get('[id="editCaretakerSubmit"]').click()
  })
  it('edit caretaker page - changes - success', () => {
    cy.visit('/app')
    cy.get('[id="nav-caretaker"]').click()
    cy.get('[id="caretaker-edit-btn"]').should('contain.text', 'Edit').click({multiple: true, force: true})
    cy.get('[class="modal-header"]').should('contain.text', 'Edit caretaker')
    cy.get('[id="caretakerNameLabel"]').clear().type('Zbyszek')
    cy.get('[id="editCaretakerSubmit"]').click()
  })
})